### ISSUE TITLE
Temps de clic 5 --> 15 min

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/pad.numerique.gouv.fr#16]
Aujourd'hui, lorsque je demande un accès, j'ai 5 minutes pour cliquer sur un lien. Cependant, ma messagerie est configurée pour faire une mise à jour chaque 15 min. Ainsi, si je ne pense pas à cliquer sur "actualiser manuellement" je suis hors délais. 

![image](https://user-images.githubusercontent.com/15428433/205923037-038e7a8c-375a-4af5-847b-466b02612e75.png)

Je pense qu'il serait une bonne pratique de passer à 15 minutes à minima.

**Comment by jdauphant** [comment]
@margot-sanchez  Le mode d'identification va changer, ça va être https://www.authentification.incubateur.net/ utilisé à la place, le délais est de 15mins à 1h. Et un code sera envoyé sur Tchap immédiatement aussi.
