### ISSUE TITLE
Modification page accueil/connexion/s'enregistrer 

### ISSUE THREAD

**Issue by rebeccadumazert** [betagouv/pad.numerique.gouv.fr#24]
Issue en référence à l'issue #23 (fermée)

### Sur la page [accueil ](https://pad.numerique.gouv.fr/)

Modifier le contenu du bouton "s'inscrire" pour le transformer en "se connecter" et ajouter un bouton "s'inscrire" qui pointe vers la bonne URL. 

Je me demande si l'onglet "historique" est pertinent lorsqu'on n'est pas encore connecté/inscrit

### Sur la page [connexion ](https://auth.pad.numerique.gouv.fr/auth/realms/padnumerique/protocol/openid-connect/auth?response_type=code&redirect_uri=https%3A%2F%2Fpad.numerique.gouv.fr%2Fauth%2Foauth2%2Fcallback&state=2VXp6mHu3FpIhh0S0TUVZu2D&client_id=dinum-pad)

Modifier le label "nom d'utilisateur" ou ajouter un placeholder dans l'imput spécifiant "adresse mail"

### Sur la page [s'enregistrer ](https://auth.pad.numerique.gouv.fr/auth/realms/padnumerique/login-actions/registration?execution=bec2b5b5-9964-4d73-aa27-01f4b1d1099e&client_id=dinum-pad&tab_id=Kffe5wEnJpU)

Afficher un message d'erreur/d'information si l'inscription n'est pas possible. Par exemple j'ai essayé de m'inscrire 4 ou 5 fois en pensant que le site ne fonctionnait pas mais l'explication c'est que j'avais déjà un compte existant avec mon adresse beta.

**Comment by tut-tuuut** [comment]
Je clôture l'issue : on n'a plus ces pages-là depuis qu'on est branché sur des fournisseurs OpenIDConnect extérieurs (Authentification/MCP)
