### ISSUE TITLE
Brancher le pad sur authentification

### ISSUE THREAD

**Issue by tut-tuuut** [betagouv/pad.numerique.gouv.fr#26]
- [ ] Configurer Sendinblue
- [ ] Configurer un compte tchap
- [ ] Créer le client sur authentification
- [ ] Créer les bonnes variables d'env sur le pad
- [ ] Redémarrer le pad

@dxb Pas urgent, mais j'aurai sûrement besoin de ton aide à un moment. :)

**Comment by dxb** [comment]
Pas de souci. 
Le point crucial est l'adresse mail authentification sur sendinblue qui doit être parametré dans le realm du keycloak.

**Comment by jdauphant** [comment]
@tut-tuuut Authentification ne support qu'un seul fournisseur mail pour le moment, c'est configure avec celui de Mailjet avec l'adresse audioconf.

Comme solutions :
-  soit adapter Authentification pour gérer plusieurs fournisseurs (ça eput être la galère si vous n'avez pas résolu le problème avec vos apples m1/m2)
- sinon il faut changer l'email par un truc du genre ***@authentification.beta.gouv.fr pour l'authentification d'Audioconf aussi, dans ce cas là, ça va peut générer un pic de support et d'erreur pour AudioConf, il faudrait le générer conjointement (il y a pas mal de travaux @estellecomment pour faire accepter l'ip et les emails venant de mailjet aux ministères/universités pour que ça n'attérisse pas dans les spams)

On peut échanger si vous avez besoin.

**Comment by tut-tuuut** [comment]
C'est fait !
