### ISSUE TITLE
ETQ utilisateur, je veux pouvoir me connecter au pad via un identifiant et mot de passe (ou un système d'auth existant)

### ISSUE THREAD

**Issue by marineb** [betagouv/pad.numerique.gouv.fr#34]
Personnellement, se connecter en devant atetndre un code via mail me fait perdre trop de temps. Ca me met en risque si j'ai besoin d'avoir accès à des notes / documents immédiatement. Et donc ne me donne pas envie de mettre des docs sur le pad. Et / ou de vouloir les sécuriser autre part. Ce qui est un peu dommage.

**Comment by tut-tuuut** [comment]
Bonjour Marine, pour info nous avons prévu de brancher AgentConnect/Mon compte pro sur le pad à l'automne. D'ici là nous gardons le système d'auth par envoi de code par mail. L'ancien système laissait trop de personnes totalement bloquées sans pouvoir récupérer leur mot de passe.

**Comment by marineb** [comment]
Ok merci !

**Comment by revolunet** [comment]
je crois bien que c'est réglé 🎉

**Comment by marineb** [comment]
Merci !
